apiVersion: apps/v1
kind: Deployment
metadata:
  name: sockjs
  labels:
    app: sockjs
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sockjs
        octopusexport: OctopusExport
    spec:
      containers:
        - name: sockjs
          image: '832256313046.dkr.ecr.eu-west-1.amazonaws.com/sockjs:latest'
          ports:
            - containerPort: 9999
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web
                topologyKey: kubernetes.io/hostname
